### ISSUE TITLE
Nodes removed from a way are not detected

### ISSUE THREAD

**Issue by zstadler** [iandees/deep-history-py#1]
OSM [way 771909611](https://www.openstreetmap.org/way/771909611) currently has 2 nodes:

![image](https://user-images.githubusercontent.com/1304610/151979447-db1b84b4-0cbf-4481-841f-f18a6786a8f5.png)

Its [Deep History](https://osm.mapki.com/history/way/771909611) looks as if it has 6 nodes:

![image](https://user-images.githubusercontent.com/1304610/151979973-79c018e2-3f8f-4748-9430-1390aea560eb.png)

As far as I understand from the [way history API](https://www.openstreetmap.org/api/0.6/way/771909611/history), the Deep History for the nodes should have been

![image](https://user-images.githubusercontent.com/1304610/151981680-5ba1880a-cb7a-4119-9359-6715f4e1a5ef.png)

Perhaps the removal of nodes was mistakenly regarded as a modification.

**Comment by iandees** [comment]
Thanks for pointing this out. I made a fix that should be better, but it's still not perfect. This visualization doesn't do a great job of showing how the node order changes. I should probably pull in little maps of what the way looked like at each version.

**Comment by zstadler** [comment]
Thanks @iandees for the super-fast fix!
I can't think of a good way to show the geometry changes. For example if the node order is reversed as part of converting a street to one-way.
