### ISSUE TITLE
Adding hyperlink for node/way/relation to osm.org

### ISSUE THREAD

**Issue by merylstreet** [iandees/deep-history-py#3]
Hi there, using your tool every day and it's amazing to get a clear view of each feature changes.
Just wanted to propose a small improvement (I currently use a bookmarklet to do it) for linking the id itself to the osm.org page. There are already osm.org hyperlinks to changeset/user but not to the id itself. That way we can get more context on osm.org.

Here is an example of what my bookmarklet does just so it's clear. The hyperlink you see points to https://www.osm.org/node/139964823
![image](https://user-images.githubusercontent.com/4256618/235314595-bcc8df5c-9b0f-4b25-b0ea-bbc8b1504589.png)

Let me know if you need more info, I believe it would be useful for everyone using https://osm.mapki.com/history/

Cheers

**Comment by iandees** [comment]
This sounds good. What about adding links to the individual version numbers across the top where the numbers are?

**Comment by merylstreet** [comment]
Yeah that's probably even better. 

I'd say it wouldn't add much for nodes but for ways, your idea would help easily visualise the changes in geometry between versions.

**Comment by merylstreet** [comment]
Not sure if it would be useful but just thought about this. Why not also adding a link to https://taginfo.openstreetmap.org/keys/... for each tag displayed?

**Comment by iandees** [comment]
Looks like the single-version pages for primitives don't exist. I added taginfo and OSM.org links though!

**Comment by merylstreet** [comment]
Thanks a lot, very quick update. Do you know how long will it take to show on Mapki?

**Comment by iandees** [comment]
I just updated it this morning. It should be visible now.
