### ISSUE TITLE
Add a flip column order button

### ISSUE THREAD

**Issue by merylstreet** [iandees/deep-history-py#7]
Been using a bookmarklet to flip the order of columns in Mapki.

This is very useful for objects with many versions where we need to scroll far to the right of the page.
Specific example here https://osm.mapki.com/history/way/69412370

Would you be able to implement something similar by any chance?

![image](https://github.com/user-attachments/assets/790ca304-4b6c-4cdc-b4bc-3af027e26e76)
![image](https://github.com/user-attachments/assets/98c3dd17-d46a-4e2f-bc25-e267792c4cac)

**Comment by iandees** [comment]
Rather than a "flip column order" button I think I would prefer to add a link that sends you all the way to the right. Would that work?

**Comment by merylstreet** [comment]
Yeah that would work as well

**Comment by iandees** [comment]
This is deployed.

Each deep history page now has a "most recent" link, which jumps to the rightmost column:

<img width="603" alt="image" src="https://github.com/user-attachments/assets/105b2a47-d4df-44dd-a777-c1bdac6fa280">

**Comment by merylstreet** [comment]
This is perfect! Cheers for the quick update
